### ISSUE TITLE
accessing functions defined in bag

### ISSUE THREAD

**Issue by afrozl** [nodeca/bag.js#9]
I notice that any functions defined in bag.js startup are no longer accessible in the global name space, eg:
<pre>bag.require(['/site.css', '/jquery.js', '/site.js'], function (err) {
  if (err) {
    console.log('loading error: ', err);
    return
  }
  // code to run after loading
  function testFunction() {
               console.log('hello');
       }
})</pre>.
How do I access these named functions as <pre>window\['testFunction'\]()</pre> no longer works?

**Comment by puzrin** [comment]
I did not changed much in bug.js last year. It just inserts css/js into the head, and it's your responsibility what to do in those scripts. It doesn't know anything about your code.

If you think this problem is related to bag.js - please provide a minimal example in test repo to reproduce. Or navigate commits history and point commit that could cause your case. But i suspect problem is not here.
